## Course: Visual Analytics for Policy and Management
###Bivariate Homework 
####Group 3: Dave Coomes, Quinhas Fernndes, Isabella Sun

#### date : 02/27/2019 
## 
##

First we load libraries and bring in the data
```{r setup}
library(ggplot2)
library(foreign)
library(haven)
knitr::opts_chunk$set(echo = TRUE, warning=TRUE, message=TRUE)

link="https://github.com/ihsun-uw/Group3_Final_Project/raw/master/child_mortality.dta"

child_mort<-read_dta(url(link))

```

Preparing the data
```{r data_prep}

df1=df

df_aggre <- aggregate(cbind(NEONAT_COMB , INFANT_COMB, U5M_COMB, birthatend, hwdensity, midwifedensity)~provname, data=df1, FUN=mean )

```

Creating a box plot
```{r echo=TRUE, warning=FALSE}
g <- ggplot(df, aes(x=reorder(provname,-U5M_COMB), y=U5M_COMB))
g + geom_boxplot(varwidth=T, fill="grey80") + 
    labs(title="Boxplot", 
         subtitle="Under Five mortality Distribuition by Region in Mozambique",
         caption="Source: DHS",
         x="Province",
         y="Under Five Mortality (per thousand)") +
   theme(panel.background = element_rect(fill = "gray98",
                                                    colour = "black"),
                    plot.caption = element_text(hjust = 0), 
                    plot.title = element_text(hjust = 0.5),
                    plot.subtitle = element_text(hjust=0.5),
                    legend.box.just = c("right","center"), 
                    axis.text.x = element_text(size=7, angle = 45, vjust = 1, hjust=1)) 

```

