## Course: Visual Analytics for Policy and Management
###Bivariate Homework 
####Group 3: Dave Coomes, Quinhas Fernndes, Isabella Sun, Long Zong

#### date : 02/27/2019 
## 
##

First we load libraries and bring in the data
```{r setup, warning=FALSE}
library(ggplot2)
library(foreign)
library(haven)
knitr::opts_chunk$set(echo = TRUE, warning=TRUE, message=TRUE)

link="https://github.com/ihsun-uw/Group3_Final_Project/raw/master/child_mortality.dta"

child_mort<-read_dta(url(link))

```


```{r data_prep, include=FALSE}

df=child_mort
df_aggre <- aggregate(cbind(NEONAT_COMB , INFANT_COMB, U5M_COMB, birthatend, hwdensity, midwifedensity)~provname, data=df, FUN=mean )

```

Creating a box plot 

```{r echo=TRUE, warning=FALSE}
g <- ggplot(df, aes(x=reorder(provname,-U5M_COMB), y=U5M_COMB))
g + geom_boxplot(varwidth=T, fill="grey80") + 
    labs(title="Under Five mortality Distribuition by Region in Mozambique", 
         caption="Source: DHS",
         x="Province",
         y="Under Five Mortality (per thousand)") +
   theme(panel.background = element_rect(fill = "gray98",
                                                    colour = "black"),
                    plot.caption = element_text(hjust = 0), 
                    plot.title = element_text(hjust = 0.5),
                    plot.subtitle = element_text(hjust=0.5),
                    legend.box.just = c("right","center"), 
                    axis.text.x = element_text(size=7, angle = 45, vjust = 1, hjust=1)) 

```


Creating a line graph

```{r warning= FALSE }

base2 = ggplot(df,aes(x=provname, y=INFANT_COMB))
mins1 = base2 + stat_summary(fun.y=min, # function for 'y' is min()
                           geom="line",
                           show.legend = T,size=1,
                           aes(group=1,col='Min'))
minsMaxs1= mins1 + stat_summary(fun.y=max,
                              geom="line",
                              linetype='dashed',
                              size=1,show.legend = F,
                              aes(group=1,col='Max'))+
  labs(title="Infant Mortality by Region in Mozambique Between 2000 to 2010",
         caption="Source: DHS",
         x="Province",
         y="Infant mortality (per thousand)",
         colour="") +             #adjusting legend title
     theme(panel.background = element_rect(fill = "gray98",
                                                    color = "black"),
                    plot.caption = element_text(hjust = 0), 
                    plot.title = element_text(hjust = 0.5),
                    plot.subtitle = element_text(hjust=0.5),
                    legend.box.just = c("right","center"), 
                    axis.text.x = element_text(size=9, angle = 40, vjust = 1, hjust=1)) 
minsMaxs1 + guides(fill=guide_legend(title="Legend"))
```

